### ISSUE TITLE
Sidekiq is too quick causing false positives

### ISSUE THREAD

**Issue by HusseinElMotayam** [twonegatives/attentive_sidekiq#7]
Thank you for attentive_sidekiq, it is very useful!

I've been using attentive_sidekiq with hundreds of thousands of jobs, and I've seen it reporting too many false-positives. I've verified that the reported jobs were properly terminated according to the logs.
I also took a look at #2 and I don't think it is the cause here.

So, looking at https://github.com/twonegatives/attentive_sidekiq/blob/dadf9be7deeba5a820ac3f2720b3b128517fc755/lib/attentive_sidekiq/middleware/server/attentionist.rb#L6
The jobs are added to the suspicious list and removed when they are done. This is good.

Now, regarding the check here https://github.com/twonegatives/attentive_sidekiq/blob/23aca046a512c4c3cb9cee579cbae6f08fdfc340/lib/attentive_sidekiq/manager.rb#L18
There is a slight chance that a job exists in the suspicious list, but by the time we reach the next statement and get the active list, the job actually terminates properly and is no longer actively being worked on by a worker. So, that's a **false positive**.

**Would it be better to change the ordering?** So we'd get the active list first, then get the suspicious list,
where:
1. If a job is active, and not suspicious, then Sidekiq was very quick at finishing up the active job and actually managed to remove it from the suspicious list. No need to do anything here because we've really seen the job as active.
2. If a job is not in the active list, but in the suspicious list, then this is a **truly dropped job**.
3. If a job appears in active and suspicious lists, fine, let's leave it until it turns out as 1 or 2.

I'd be more than happy to make a pull-request if you confirm that this logic is correct.

Thank you!

**Comment by twonegatives** [comment]
Hello and thank you for giving attentive_sidekiq a try!
I should agree that some kind of a race condition may occur here.
Please double check that in case of reverse lines ordering new jobs are added to
```ruby
Sidekiq::Workers.new.to_a.map{|i| i[2]["payload"]}
```
*before* a call to middleware happens:
```ruby
class Attentionist
  def call(worker_instance, item, queue)
    Suspicious.add(item)
```
In this case we won't face the opposite issue with jobs added to suspicious but not started yet...

**Comment by HusseinElMotayam** [comment]
Your point makes sense, if we change the ordering, we'd fall into the opposite case.

I proposed an additional iteration on the 'new' suspicious list, where if a job appears in the first list, but not the second, we would disregard it as a lost job since it is no longer suspicious (terminated properly).

**Comment by pchaganti** [comment]
👍

**Comment by twonegatives** [comment]
@HusseinElMotayam thank you, merged to master. 
Please give it a try in your environment and update me if your issue is resolved by this.

**Comment by HusseinElMotayam** [comment]
@twonegatives Great news, thank you.
Sure, I'll let you know the results, but that would probably happen in a few months.
