### ISSUE TITLE
Incorrectly detecting many lost jobs

### ISSUE THREAD

**Issue by oskarpearson** [twonegatives/attentive_sidekiq#9]
Hi

Thanks for the work on this gem - it seems to be pretty much exactly what we want :)

Unfortunately, though, it's detecting many jobs as disappeared, even when they are successfully executing. Any suggestions on what I should investigate to figure out why?

Note that I've not specified any `attentive` key in sidekiq.yml, so I expect it should be relying on the default values. Indeed, running `AttentiveSidekiq::Manager.instance.send(:options)` in some sidekiq middleware logs returns `{:execution_interval=>600, :timeout_interval=>60}`

Here's an example log fragment. The job starts running, and a very short time later it's classified as disappeared. The job then successfully finishes a few seconds later.

This doesn't happen every time, but as we process a large number of jobs we quickly end up with 30,000+ jobs in our disappeared jobs list.

```
Mar 21 17:00:46 [redacted]-worker-2-9247e93b: 2018-03-21T17:00:46.800Z 165 TID-gqes5o1n5 TrackingWorker JID-7eb868b7973ab454311f21da INFO: start
Mar 21 17:00:47 [redacted]-worker-2-9247e93b: 2018-03-21T17:00:46.982Z 165 TID-our6xz2mx INFO: 2018-03-21 17:00:46 +0000 [AttentiveSidekiq] Finished updating with result [{"class"=>"TrackingWorker", "args"=>["signed_in", 357178, {"type"=>"email", "source"=>"Website"}], "retry"=>true, "queue"=>"low", "jid"=>"7eb868b7973ab454311f21da", "created_at"=>1521651646.7974627, "enqueued_at"=>1521651646.7975132}]
Mar 21 17:00:47 [redacted]-worker-2-9247e93b: 2018-03-21T17:00:47.268Z 165 TID-gqes5o1n5 TrackingWorker JID-7eb868b7973ab454311f21da INFO: done: 0.468 sec
```

Environment:

- Ruby 2.5.0
- attentive_sidekiq 0.3.3
- Sidekiq 5.1.1
- Rails 5.1.5

Thanks for any help you might be able to provide.

**Comment by twonegatives** [comment]
Hi @oskarpearson. We've had a [discussion](https://github.com/twonegatives/attentive_sidekiq/issues/7) on a similar topic recently and ended up implementing some additional checks in attentive_sidekiq v.0.3.3. Do you use the lateset gem version?

**Comment by twonegatives** [comment]
Ah, I see, you mentioned it's the latest one you use...

**Comment by oskarpearson** [comment]
@twonegatives Thanks for taking the time to respond to me! Do you think it's worth me trying v0.3.2? I can do it pretty easily, if so.

**Comment by twonegatives** [comment]
Actually no, I don't think that downgrade could help with your issue.
May be you could provide some kind of minimalistic `rails` application which could confirm this issue on run?

**Comment by oskarpearson** [comment]
I've done a bit of reading of the code, and am pretty sure that this is a race condition in the below circumstance.

```
Time|Action
00:00:00.00|Item 'I' added to the queue, and the Attentionist::Server middleware  adds the item to the Suspicious list
00:00:01.01|AttentiveSidekiq::Manager.update_disappeared_jobs runs
00:00:01.02|AttentiveSidekiq::Manager populates those_lost with the job id for 'I'
00:00:01.02|AttentiveSidekiq::Manager re-fetches suspicious list; job ID 'I' still hasn't started
00:00:01.02|AttentiveSidekiq::Manager adds the item to the disappeared list, and removes it from the suspicious list
00:00:02.00|Job starts executing
```

I think we can replicate this as follows:

1. Create a sidekiq service with concurrency of 1
2. Queue a long running job (job 1) (> 10 minutes)
3. After a moment, queue another job (job 2). This should add to the Suspicious jobs list but not start it.
4. Wait for `Concurrent::TimerTask` to execute after 10 minutes.

Here job 2 won't be active, so my understanding is that it wouldn't be in `AttentiveSidekiq::Active.job_ids` but would be in `AttentiveSidekiq::Suspicious.jobs` and would move the item to `disappeared`

**Comment by oskarpearson** [comment]
I've deleted an incorrect comment that I put in here (after discussion with a colleague). Sorry about that.

I'm going to experiment with things and submit a trace / PR / example to fix things here.

**Comment by twonegatives** [comment]
Closing this for now due to lack of input. Please feel free to reopen once any confirmation could be provided.
